export enum TextContent {
    Uri = 'URI',
    UriPrefix = 'URI Prefix',
    Shorten = 'Shorten',
    Copy = 'Copy',
    CopiedToClipboard = 'Short link is copied to clipboard!',
    CopyToClipboardFailed = 'Copy to clipboard failed!',
    ShortenFieldValidationMessage = 'Please enter a valid URI',
    NotFoundTitle = '404',
    NotFoundDescription = 'Not Found!',
    GoHome = 'Go to homepage',
    AboutTitle = 'Tech Stacks',
    AboutTechStack = 'This is an open-source application created with .NET Core / Angular + RxJS & Material UI for the ✨ style.',
    AboutBug = 'Found a 🕷️? Send a',
    Feedback = 'feedback',
}
